name: Claude PR Assistant

on:
  issue_comment:
    types: [created, edited]
  pull_request_review:
    types: [submitted, edited]
  issues:
    types: [opened, edited]

jobs:
  claude:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}